stages:
  - build

variables:
  IMAGE_NAME: medusa-proxy
  IMAGE_VERSION: 0.1.3
  ACCOUNT_NAME: datawookie
  TAG_LATEST: $ACCOUNT_NAME/$IMAGE_NAME:latest
  TAG_COMMIT: $ACCOUNT_NAME/$IMAGE_NAME:$IMAGE_VERSION
  DOCKER_REGISTRY_USER: $ACCOUNT_NAME
  DOCKER_REGISTRY: docker.io
  DOCKER_TLS_CERTDIR: ""

before_script:
  - export
  # DOCKER_REGISTRY_PASSWORD is in CI/CD settings.
  - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD" $DOCKER_REGISTRY

build:
  image: docker:stable
  stage: build
  only:
    - master
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  services:
    - docker:dind
  script:
    - docker info
    - docker pull $TAG_LATEST || true
    - docker build --cache-from $TAG_LATEST -t $TAG_COMMIT -t $TAG_LATEST .
    - docker push $TAG_COMMIT
    - docker push $TAG_LATEST
